# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dwellir < Formula
  desc "Dwellir CLI — Blockchain RPC infrastructure from your terminal"
  homepage "https://dwellir.com"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.10/dwellir_darwin_amd64.tar.gz"
      sha256 "5c7cf5d6ed73c8298834d9f0cb68c2ff59cf2f73cf515c10a6625ca3a1388dab"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.10/dwellir_darwin_arm64.tar.gz"
      sha256 "6c0cfe0795de3f3e0f1cdbc9233c5052fd886601835b8b43dae52bb41b6513d6"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.10/dwellir_linux_amd64.tar.gz"
      sha256 "5a7b2b4ee669500aa47e95037bb8b3b3c0024763ffcd52adca3aaa228ca7c372"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.10/dwellir_linux_arm64.tar.gz"
      sha256 "fc97894bcc04ad8c16f283307cd4e254ec35a5103ea88439e3390fcc12eb6d3a"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  test do
    system "#{bin}/dwellir", "version"
  end
end
