# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dwellir < Formula
  desc "Dwellir CLI — Blockchain RPC infrastructure from your terminal"
  homepage "https://dwellir.com"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.20/dwellir_darwin_amd64.tar.gz"
      sha256 "6da408531367266e5bbba3be2098a97c88c76659c29dd37375a473b5cd7fb54e"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.20/dwellir_darwin_arm64.tar.gz"
      sha256 "ff7421052395d5a4823407c3128568889d1572105650c29ba0331cf2fb5c1700"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.20/dwellir_linux_amd64.tar.gz"
      sha256 "2c9753b83ca5886238569bca4760e320930c5804e39422cd8106dde9fe0cad55"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.20/dwellir_linux_arm64.tar.gz"
      sha256 "5eb7f2e6e286987662afa23061abda2ab835a856cafb021a8d9fa99cb985e766"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  test do
    system "#{bin}/dwellir", "version"
  end
end
