# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dwellir < Formula
  desc "Dwellir CLI — Blockchain RPC infrastructure from your terminal"
  homepage "https://dwellir.com"
  version "0.1.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.28/dwellir_darwin_amd64.tar.gz"
      sha256 "40868f5682bae35c280f1e30ddbd442129b3406c027e3d38ca39633a191e75c7"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.28/dwellir_darwin_arm64.tar.gz"
      sha256 "1f2938bc80285a7e0fa93106736fc568f2c4eed4a185933226639d007f871999"

      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.28/dwellir_linux_amd64.tar.gz"
      sha256 "08f25fc310549a96652341280f45b016d28451ddd63422984c67bd80e1967178"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dwellir-public/cli/releases/download/v0.1.28/dwellir_linux_arm64.tar.gz"
      sha256 "6395ccd54a34d5d1c6dcc4fd337ba12bee70919a0573a719a686120e9787a5a5"
      define_method(:install) do
        bin.install "dwellir"
      end
    end
  end

  test do
    system "#{bin}/dwellir", "version"
  end
end
